-- Auto-generated from the HTML tool's existing 468-entry database.
-- Run this AFTER supabase-schema-v2.sql. Safe to re-run (upserts on name).

insert into fragrances (name, tier, source) values
  ('Parfums de Marly Layton', 'oriental', 'curated'),
  ('Parfums de Marly Herod', 'oriental', 'curated'),
  ('Parfums de Marly Delina', 'floral', 'curated'),
  ('Alfred Dunhill Desire', 'fresh', 'curated'),
  ('Dunhill Desire for a Man', 'fresh', 'curated'),
  ('Xerjoff Naxos', 'gourmand', 'curated'),
  ('Xerjoff 40 Knots', 'fresh', 'curated'),
  ('Xerjoff Erba Pura', 'fresh', 'curated'),
  ('Clive Christian Crown Matsukita', 'oriental', 'curated'),
  ('Rain Tea', 'fresh', 'curated'),
  ('God of Fire', 'oriental', 'curated'),
  ('RWA', 'oriental', 'curated'),
  ('Wulong Cha', 'fresh', 'curated'),
  ('YSL MYSLF', 'fresh', 'curated'),
  ('Ex Nihilo Blue Talisman', 'floral', 'curated'),
  ('Armani Code Parfum', 'oriental', 'curated'),
  ('JPG Le Beau Le Parfum', 'gourmand', 'curated'),
  ('Black XS L''Excès', 'oriental', 'curated'),
  ('Dior Sauvage', 'fresh', 'curated'),
  ('Dior Sauvage Elixir', 'oriental', 'curated'),
  ('Bleu de Chanel', 'fresh', 'curated'),
  ('Chanel No.5', 'floral', 'curated'),
  ('Chanel Coco Mademoiselle', 'floral', 'curated'),
  ('Chanel Chance', 'floral', 'curated'),
  ('Creed Aventus', 'floral', 'curated'),
  ('Creed Green Irish Tweed', 'fresh', 'curated'),
  ('Maison Francis Kurkdjian Baccarat Rouge 540', 'oriental', 'curated'),
  ('Maison Francis Kurkdjian Grand Soir', 'oriental', 'curated'),
  ('Maison Francis Kurkdjian Aqua Universalis', 'fresh', 'curated'),
  ('Yves Saint Laurent Black Opium', 'gourmand', 'curated'),
  ('Carolina Herrera Good Girl', 'gourmand', 'curated'),
  ('Carolina Herrera 212 VIP', 'gourmand', 'curated'),
  ('Lancome La Vie Est Belle', 'gourmand', 'curated'),
  ('Paco Rabanne One Million', 'gourmand', 'curated'),
  ('Giorgio Armani Acqua di Gio', 'fresh', 'curated'),
  ('Dolce Gabbana Light Blue', 'fresh', 'curated'),
  ('Dior J''adore', 'floral', 'curated'),
  ('Dior Miss Dior', 'floral', 'curated'),
  ('Viktor Rolf Flowerbomb', 'floral', 'curated'),
  ('Thierry Mugler Alien', 'oriental', 'curated'),
  ('Thierry Mugler Angel', 'gourmand', 'curated'),
  ('Yves Saint Laurent Opium', 'oriental', 'curated'),
  ('Guerlain Shalimar', 'oriental', 'curated'),
  ('Guerlain Habit Rouge', 'oriental', 'curated'),
  ('Tom Ford Tobacco Vanille', 'gourmand', 'curated'),
  ('Tom Ford Oud Wood', 'woody', 'curated'),
  ('Tom Ford Black Orchid', 'gourmand', 'curated'),
  ('Tom Ford Vanille 44', 'gourmand', 'curated'),
  ('Yves Saint Laurent Kouros', 'oriental', 'curated'),
  ('Hermès Terre d''Hermès', 'fresh', 'curated'),
  ('Jo Malone English Pear Freesia', 'fresh', 'curated'),
  ('Jo Malone Wood Sage Sea Salt', 'fresh', 'curated'),
  ('Le Labo Santal 33', 'woody', 'curated'),
  ('Le Labo Another 13', 'floral', 'curated'),
  ('Byredo Gypsy Water', 'fresh', 'curated'),
  ('Byredo Bal d''Afrique', 'fresh', 'curated'),
  ('Versace Eros', 'fresh', 'curated'),
  ('Versace Dylan Blue', 'fresh', 'curated'),
  ('Prada Luna Rossa', 'fresh', 'curated'),
  ('Hugo Boss Bottled', 'fresh', 'curated'),
  ('Calvin Klein Eternity', 'floral', 'curated'),
  ('Gucci Bloom', 'floral', 'curated'),
  ('Gucci Guilty', 'floral', 'curated'),
  ('Burberry Her', 'gourmand', 'curated'),
  ('Valentino Born in Roma', 'gourmand', 'curated'),
  ('Jean Paul Gaultier Le Male', 'oriental', 'curated'),
  ('Ralph Lauren Polo Blue', 'fresh', 'curated'),
  ('Issey Miyake L''Eau d''Issey', 'fresh', 'curated'),
  ('Davidoff Cool Water', 'fresh', 'curated'),
  ('Azzaro Chrome', 'fresh', 'curated'),
  ('Givenchy Gentleman', 'oriental', 'curated'),
  ('Montblanc Explorer', 'oriental', 'curated'),
  ('Narciso Rodriguez For Her', 'floral', 'curated'),
  ('Escentric Molecules Molecule 01', 'fresh', 'curated'),
  ('Nishane Hacivat', 'floral', 'curated'),
  ('Nishane Ani', 'fresh', 'curated'),
  ('Amouage Interlude Man', 'oriental', 'curated'),
  ('Amouage Reflection Man', 'floral', 'curated'),
  ('Initio Oud for Greatness', 'oriental', 'curated'),
  ('Initio Side Effect', 'gourmand', 'curated'),
  ('Kilian Good Girl Gone Bad', 'floral', 'curated'),
  ('Kilian Black Phantom', 'gourmand', 'curated'),
  ('Sospiro Erba Blu', 'fresh', 'curated'),
  ('Montale Intense Cafe', 'gourmand', 'curated'),
  ('Montale Aoud Lavande', 'oriental', 'curated'),
  ('Mancera Cedrat Boise', 'fresh', 'curated'),
  ('Nasomatto Black Afgano', 'oriental', 'curated'),
  ('Xerjoff Uden', 'oriental', 'curated'),
  ('Xerjoff Renaissance Overdose', 'gourmand', 'curated'),
  ('Xerjoff Alexandria II', 'oriental', 'curated'),
  ('Xerjoff Homage', 'oriental', 'curated'),
  ('Amouage Jubilation XXV', 'oriental', 'curated'),
  ('Amouage Jubilation 25 Woman', 'oriental', 'curated'),
  ('Amouage Portrayal Man', 'floral', 'curated'),
  ('Amouage Honour Man', 'fresh', 'curated'),
  ('Amouage Memoir Man', 'oriental', 'curated'),
  ('Nishane Ege', 'fresh', 'curated'),
  ('Nishane Colognisant', 'fresh', 'curated'),
  ('Initio Musk Therapy', 'floral', 'curated'),
  ('Initio Paragon', 'oriental', 'curated'),
  ('Initio Rehab', 'gourmand', 'curated'),
  ('Maison Francis Kurkdjian Oud Satin Mood', 'oriental', 'curated'),
  ('Maison Francis Kurkdjian Gentle Fluidity Gold', 'oriental', 'curated'),
  ('Maison Francis Kurkdjian Gentle Fluidity Silver', 'fresh', 'curated'),
  ('Maison Francis Kurkdjian 724', 'floral', 'curated'),
  ('Mancera Roses Vanille', 'gourmand', 'curated'),
  ('Mancera Instant Crush', 'gourmand', 'curated'),
  ('Mancera Aoud Lemon Mood', 'fresh', 'curated'),
  ('Montale Chocolate Greedy', 'gourmand', 'curated'),
  ('Montale Black Aoud', 'oriental', 'curated'),
  ('Montale Dark Aoud', 'oriental', 'curated'),
  ('Kilian Love Don''t Be Shy', 'gourmand', 'curated'),
  ('Kilian Straight to Heaven', 'oriental', 'curated'),
  ('Kilian Angels'' Share', 'gourmand', 'curated'),
  ('Kilian Rose Oud', 'oriental', 'curated'),
  ('Roja Elysium', 'floral', 'curated'),
  ('Roja Danger', 'oriental', 'curated'),
  ('Roja Enigma', 'oriental', 'curated'),
  ('Creed Silver Mountain Water', 'fresh', 'curated'),
  ('Creed Millesime Imperial', 'fresh', 'curated'),
  ('Creed Viking', 'fresh', 'curated'),
  ('Creed Royal Oud', 'oriental', 'curated'),
  ('Guerlain Mon Guerlain', 'floral', 'curated'),
  ('Guerlain L''Homme Ideal', 'gourmand', 'curated'),
  ('Guerlain Vetiver', 'woody', 'curated'),
  ('Guerlain Insolence', 'floral', 'curated'),
  ('Chanel Bleu de Chanel Parfum', 'oriental', 'curated'),
  ('Chanel Allure Homme Sport', 'fresh', 'curated'),
  ('Chanel Egoiste', 'oriental', 'curated'),
  ('Chanel Antaeus', 'oriental', 'curated'),
  ('Dior Homme Intense', 'oriental', 'curated'),
  ('Dior Fahrenheit', 'fresh', 'curated'),
  ('Dior Eau Sauvage', 'fresh', 'curated'),
  ('Dior Poison', 'oriental', 'curated'),
  ('Yves Saint Laurent La Nuit de L''Homme', 'oriental', 'curated'),
  ('Yves Saint Laurent Y EDP', 'fresh', 'curated'),
  ('Yves Saint Laurent Libre', 'floral', 'curated'),
  ('Versace Pour Homme', 'fresh', 'curated'),
  ('Versace Bright Crystal', 'floral', 'curated'),
  ('Prada Luna Rossa Carbon', 'fresh', 'curated'),
  ('Prada Candy', 'gourmand', 'curated'),
  ('Prada Paradoxe', 'floral', 'curated'),
  ('Bvlgari Man in Black', 'oriental', 'curated'),
  ('Bvlgari Aqva Pour Homme', 'fresh', 'curated'),
  ('Bvlgari Omnia Crystalline', 'floral', 'curated'),
  ('Hermès Un Jardin sur le Nil', 'fresh', 'curated'),
  ('Hermès Terre d''Hermès Parfum', 'oriental', 'curated'),
  ('Burberry Brit', 'fresh', 'curated'),
  ('Burberry Weekend', 'fresh', 'curated'),
  ('Calvin Klein CK One', 'fresh', 'curated'),
  ('Calvin Klein Obsession', 'oriental', 'curated'),
  ('Calvin Klein Euphoria', 'gourmand', 'curated'),
  ('Ariana Grande Cloud', 'gourmand', 'curated'),
  ('Britney Spears Fantasy', 'gourmand', 'curated'),
  ('Justin Bieber Someday', 'floral', 'curated'),
  ('Rihanna Reb''l Fleur', 'floral', 'curated'),
  ('Katy Perry Killer Queen', 'gourmand', 'curated'),
  ('Zoologist Bat', 'oriental', 'curated'),
  ('Zoologist Civet', 'oriental', 'curated'),
  ('DS Durga Debaser', 'fresh', 'curated'),
  ('Etat Libre d''Orange Rien', 'oriental', 'curated'),
  ('Etat Libre d''Orange Fat Electrician', 'gourmand', 'curated'),
  ('Comme des Garcons Wonderwood', 'oriental', 'curated'),
  ('Comme des Garcons 2 Man', 'fresh', 'curated'),
  ('Frederic Malle Portrait of a Lady', 'oriental', 'curated'),
  ('Frederic Malle Musc Ravageur', 'oriental', 'curated'),
  ('Diptyque Philosykos', 'fresh', 'curated'),
  ('Diptyque Tam Dao', 'oriental', 'curated'),
  ('Acqua di Parma Colonia', 'fresh', 'curated'),
  ('Acqua di Parma Blu Mediterraneo Fico', 'fresh', 'curated'),
  ('Sol de Janeiro Cheirosa 62', 'gourmand', 'curated'),
  ('Glossier You', 'floral', 'curated'),
  ('Phlur Missing Person', 'floral', 'curated'),
  ('Chanel Pour Monsieur', 'fresh', 'curated'),
  ('Chanel Allure Homme Edition Blanche', 'fresh', 'curated'),
  ('Chanel Sycomore', 'woody', 'curated'),
  ('Chanel Cristalle', 'fresh', 'curated'),
  ('Chanel Gabrielle', 'floral', 'curated'),
  ('Chanel Chance Eau Fraiche', 'fresh', 'curated'),
  ('Chanel Chance Eau Tendre', 'floral', 'curated'),
  ('Chanel No.19', 'floral', 'curated'),
  ('Chanel Coromandel', 'oriental', 'curated'),
  ('Chanel Allure Homme', 'fresh', 'curated'),
  ('Dior Sauvage Parfum', 'oriental', 'curated'),
  ('Dior Homme Cologne', 'fresh', 'curated'),
  ('Dior Miss Dior Blooming Bouquet', 'floral', 'curated'),
  ('Dior Addict', 'gourmand', 'curated'),
  ('Dior Hypnotic Poison', 'gourmand', 'curated'),
  ('Dior Dolce Vita', 'floral', 'curated'),
  ('Dior Joy', 'floral', 'curated'),
  ('Dior Diorissimo', 'floral', 'curated'),
  ('Yves Saint Laurent Opium Black', 'oriental', 'curated'),
  ('Yves Saint Laurent Rive Gauche', 'fresh', 'curated'),
  ('Yves Saint Laurent Elle', 'floral', 'curated'),
  ('Yves Saint Laurent In Love Again', 'floral', 'curated'),
  ('Guerlain Habit Rouge Eau de Parfum', 'oriental', 'curated'),
  ('Guerlain Guerlain Homme', 'fresh', 'curated'),
  ('Guerlain Idylle', 'floral', 'curated'),
  ('Guerlain La Petite Robe Noire', 'gourmand', 'curated'),
  ('Guerlain Spiritueuse Double Vanille', 'gourmand', 'curated'),
  ('Guerlain Encens Mythique d''Orient', 'oriental', 'curated'),
  ('Guerlain Samsara', 'oriental', 'curated'),
  ('Guerlain Mitsouko', 'oriental', 'curated'),
  ('Guerlain Jicky', 'oriental', 'curated'),
  ('Hermès Terre d''Hermès Eau Intense Vetiver', 'woody', 'curated'),
  ('Hermès Eau des Merveilles', 'fresh', 'curated'),
  ('Hermès Voyage d''Hermès', 'fresh', 'curated'),
  ('Hermès Kelly Calèche', 'floral', 'curated'),
  ('Tom Ford Noir Extreme', 'oriental', 'curated'),
  ('Tom Ford Fucking Fabulous', 'oriental', 'curated'),
  ('Tom Ford Lost Cherry', 'gourmand', 'curated'),
  ('Tom Ford Soleil Blanc', 'gourmand', 'curated'),
  ('Tom Ford Neroli Portofino', 'fresh', 'curated'),
  ('Tom Ford Grey Vetiver', 'woody', 'curated'),
  ('Tom Ford Café Rose', 'gourmand', 'curated'),
  ('Tom Ford Velvet Orchid', 'gourmand', 'curated'),
  ('Tom Ford Ombre Leather', 'oriental', 'curated'),
  ('Tom Ford Tobacco Oud', 'oriental', 'curated'),
  ('Tom Ford Bitter Peach', 'gourmand', 'curated'),
  ('Tom Ford White Patchouli', 'floral', 'curated'),
  ('Le Labo Rose 31', 'floral', 'curated'),
  ('Le Labo Thé Noir 29', 'oriental', 'curated'),
  ('Le Labo Vetiver 46', 'woody', 'curated'),
  ('Le Labo Bergamote 22', 'fresh', 'curated'),
  ('Le Labo Santal 26', 'woody', 'curated'),
  ('Byredo Mojave Ghost', 'fresh', 'curated'),
  ('Byredo Blanche', 'floral', 'curated'),
  ('Byredo Rose of No Man''s Land', 'floral', 'curated'),
  ('Byredo Black Saffron', 'oriental', 'curated'),
  ('Byredo Bibliothèque', 'oriental', 'curated'),
  ('Maison Francis Kurkdjian Amyris Femme', 'floral', 'curated'),
  ('Maison Francis Kurkdjian Amyris Homme', 'fresh', 'curated'),
  ('Maison Francis Kurkdjian Baccarat Rouge 540 Extrait', 'oriental', 'curated'),
  ('Maison Francis Kurkdjian A La Rose', 'floral', 'curated'),
  ('Xerjoff More Than Words', 'gourmand', 'curated'),
  ('Xerjoff Accento', 'floral', 'curated'),
  ('Xerjoff Ivory Route', 'oriental', 'curated'),
  ('Xerjoff Kalahari', 'oriental', 'curated'),
  ('Xerjoff Zafar', 'oriental', 'curated'),
  ('Xerjoff Tony Iommi Monkey Special', 'gourmand', 'curated'),
  ('Viktor&Rolf Spicebomb Extreme', 'gourmand', 'curated'),
  ('Amouage Interlude Woman', 'oriental', 'curated'),
  ('Amouage Epic Man', 'oriental', 'curated'),
  ('Amouage Epic Woman', 'oriental', 'curated'),
  ('Amouage Lyric Man', 'oriental', 'curated'),
  ('Amouage Lyric Woman', 'floral', 'curated'),
  ('Amouage Overture Man', 'fresh', 'curated'),
  ('Amouage Journey Man', 'oriental', 'curated'),
  ('Parfums de Marly Layton Exclusif', 'oriental', 'curated'),
  ('Parfums de Marly Pegasus', 'gourmand', 'curated'),
  ('Parfums de Marly Percival', 'fresh', 'curated'),
  ('Parfums de Marly Galloway', 'fresh', 'curated'),
  ('Parfums de Marly Kalan', 'gourmand', 'curated'),
  ('Parfums de Marly Althair', 'fresh', 'curated'),
  ('Parfums de Marly Greenley', 'fresh', 'curated'),
  ('Parfums de Marly Carlisle', 'gourmand', 'curated'),
  ('Parfums de Marly Oriental', 'oriental', 'curated'),
  ('Nishane Hundred Silent Ways', 'floral', 'curated'),
  ('Nishane B-703', 'oriental', 'curated'),
  ('Nishane Vain Woman', 'floral', 'curated'),
  ('Nishane Extrait d''Orphee', 'gourmand', 'curated'),
  ('Creed Aventus Cologne', 'fresh', 'curated'),
  ('Creed Original Vetiver', 'woody', 'curated'),
  ('Creed Original Santal', 'woody', 'curated'),
  ('Creed Spice and Wood', 'oriental', 'curated'),
  ('Creed Himalaya', 'fresh', 'curated'),
  ('Creed Bois du Portugal', 'woody', 'curated'),
  ('Roja Elixir Pour Homme', 'oriental', 'curated'),
  ('Roja Amber', 'oriental', 'curated'),
  ('Roja Reckless', 'floral', 'curated'),
  ('Roja Diaghilev', 'oriental', 'curated'),
  ('Roja Musk', 'oriental', 'curated'),
  ('Initio Oud for Happiness', 'oriental', 'curated'),
  ('Initio High Frequency', 'fresh', 'curated'),
  ('Initio Atomic Rose', 'floral', 'curated'),
  ('Initio Blessed Baraka', 'oriental', 'curated'),
  ('Montale Aoud Musk', 'oriental', 'curated'),
  ('Montale Arabians', 'oriental', 'curated'),
  ('Montale Intense Tiare', 'floral', 'curated'),
  ('Montale Dark Purple', 'gourmand', 'curated'),
  ('Mancera Black Madness', 'oriental', 'curated'),
  ('Mancera Red Tobacco', 'oriental', 'curated'),
  ('Mancera Cedrat Boise Intense', 'fresh', 'curated'),
  ('Mancera Tonka Cola', 'gourmand', 'curated'),
  ('Kilian Playing with the Devil', 'gourmand', 'curated'),
  ('Kilian Smoke for the Soul', 'oriental', 'curated'),
  ('Kilian Sunkissed Goddess', 'gourmand', 'curated'),
  ('Kilian Water Calligraphy', 'fresh', 'curated'),
  ('Lattafa Qadi', 'oriental', 'curated'),
  ('Lattafa Ard Al Zaafaran Sheikh Al Shuyukh', 'oriental', 'curated'),
  ('Lattafa Bade''e Al Oud Prive', 'oriental', 'curated'),
  ('Lattafa Ana Zaki', 'gourmand', 'curated'),
  ('Lattafa Sheikh', 'oriental', 'curated'),
  ('Lattafa Fakhar Extrait', 'oriental', 'curated'),
  ('Lattafa Yara Moi', 'gourmand', 'curated'),
  ('Lattafa Yara Tous', 'gourmand', 'curated'),
  ('Lattafa Khamrah Qahwa', 'gourmand', 'curated'),
  ('Lattafa Eclaire', 'gourmand', 'curated'),
  ('Lattafa Emaan', 'floral', 'curated'),
  ('Lattafa Malaki', 'oriental', 'curated'),
  ('Armaf Club de Nuit Woman', 'floral', 'curated'),
  ('Armaf Club de Nuit Blue', 'fresh', 'curated'),
  ('Armaf Tag Him', 'fresh', 'curated'),
  ('Armaf Sillage', 'oriental', 'curated'),
  ('Al Haramain Obsession', 'oriental', 'curated'),
  ('Al Haramain Sarab', 'oriental', 'curated'),
  ('Al Haramain Bade''e Al Oud', 'oriental', 'curated'),
  ('Al Haramain Musk Al Ghazlan', 'floral', 'curated'),
  ('Ajmal Amber Musk', 'oriental', 'curated'),
  ('Ajmal Aromatic', 'fresh', 'curated'),
  ('Ajmal Ehsaas', 'floral', 'curated'),
  ('Ajmal Musk Al Shooq', 'floral', 'curated'),
  ('Ajmal Wisal Dhahab', 'oriental', 'curated'),
  ('Rasasi Wardat Al Sultan', 'floral', 'curated'),
  ('Rasasi Dahn Al Oudh', 'oriental', 'curated'),
  ('Rasasi Ta''if', 'floral', 'curated'),
  ('Rasasi Al Wisam', 'oriental', 'curated'),
  ('Swiss Arabian Oud Al Dahab', 'oriental', 'curated'),
  ('Swiss Arabian Kalemat', 'oriental', 'curated'),
  ('Swiss Arabian Sultana', 'floral', 'curated'),
  ('Swiss Arabian Karam', 'oriental', 'curated'),
  ('Afnan 9pm Fakhar', 'fresh', 'curated'),
  ('Afnan Highness', 'oriental', 'curated'),
  ('Afnan Turathi', 'oriental', 'curated'),
  ('Nabeel Musk', 'floral', 'curated'),
  ('Hind Al Oud', 'oriental', 'curated'),
  ('Beyonce Heat', 'gourmand', 'curated'),
  ('Paris Hilton', 'floral', 'curated'),
  ('Selena Gomez Rare', 'floral', 'curated'),
  ('Taylor Swift Wonderstruck', 'floral', 'curated'),
  ('Lady Gaga Fame', 'oriental', 'curated'),
  ('David Beckham Instinct', 'fresh', 'curated'),
  ('Victoria''s Secret Bombshell', 'floral', 'curated'),
  ('Old Spice Original', 'fresh', 'curated'),
  ('Axe Dark Temptation', 'gourmand', 'curated'),
  ('Bath Body Works Japanese Cherry Blossom', 'floral', 'curated'),
  ('Caron Pour un Homme', 'fresh', 'curated'),
  ('Coty Chypre', 'oriental', 'curated'),
  ('Estée Lauder Youth Dew', 'oriental', 'curated'),
  ('Estée Lauder Beautiful', 'floral', 'curated'),
  ('Clinique Aromatics Elixir', 'oriental', 'curated'),
  ('Nina Ricci L''Air du Temps', 'floral', 'curated'),
  ('Elizabeth Arden Red Door', 'floral', 'curated'),
  ('Revlon Charlie', 'fresh', 'curated'),
  ('Lattafa Khamrah', 'oriental', 'curated'),
  ('Lattafa Yara', 'gourmand', 'curated'),
  ('Lattafa Ana Abiyedh', 'floral', 'curated'),
  ('Lattafa Fakhar', 'fresh', 'curated'),
  ('Lattafa Oud Mood', 'oriental', 'curated'),
  ('Lattafa Asad', 'oriental', 'curated'),
  ('Lattafa Raghba', 'oriental', 'curated'),
  ('Armaf Club de Nuit Intense Man', 'fresh', 'curated'),
  ('Armaf Club de Nuit Untold', 'fresh', 'curated'),
  ('Ajmal Wisal', 'oriental', 'curated'),
  ('Rasasi Hawas', 'fresh', 'curated'),
  ('Al Haramain Amber Oud', 'oriental', 'curated'),
  ('Al Haramain L''Aventure', 'gourmand', 'curated'),
  ('Al Haramain Junoon', 'oriental', 'curated'),
  ('Swiss Arabian Shaghaf Oud', 'oriental', 'curated'),
  ('Swiss Arabian Layali Rashid', 'oriental', 'curated'),
  ('Lattafa Qaed Al Fursan', 'oriental', 'curated'),
  ('Lattafa Shaheen', 'oriental', 'curated'),
  ('Lattafa Bade''e Al Oud Sweet Delight', 'gourmand', 'curated'),
  ('Lattafa Maahir', 'fresh', 'curated'),
  ('Lattafa Hayaati', 'gourmand', 'curated'),
  ('Lattafa Velvet Oud', 'oriental', 'curated'),
  ('Lattafa Perfect Man', 'fresh', 'curated'),
  ('Lattafa Ajwad', 'oriental', 'curated'),
  ('Lattafa Opulent Oud', 'oriental', 'curated'),
  ('Lattafa Pride Al Qud', 'oriental', 'curated'),
  ('Armaf Tres Nuit', 'oriental', 'curated'),
  ('Armaf Niche Vanilla Oud', 'gourmand', 'curated'),
  ('Armaf Derby', 'fresh', 'curated'),
  ('Armaf Odyssey Mandarin Sky', 'fresh', 'curated'),
  ('Ajmal Amber Wood', 'oriental', 'curated'),
  ('Ajmal Dahn Al Oudh', 'oriental', 'curated'),
  ('Ajmal Evoke', 'floral', 'curated'),
  ('Rasasi Shuhrah', 'gourmand', 'curated'),
  ('Rasasi Fakhr Al Rasasi', 'oriental', 'curated'),
  ('Rasasi La Yuqawam', 'oriental', 'curated'),
  ('Afnan 9pm', 'gourmand', 'curated'),
  ('Afnan Supremacy Silver', 'fresh', 'curated'),
  ('Afnan Supremacy Not Only Intense', 'oriental', 'curated'),
  ('My Perfumes Amber Musk', 'oriental', 'curated'),
  ('Fragrance World Nafas', 'oriental', 'curated'),
  ('Al Rehab Musk', 'floral', 'curated'),
  ('Al Rehab White Musk', 'floral', 'curated'),
  ('Nabeel Oud', 'oriental', 'curated'),
  ('Surrati Sultan', 'oriental', 'curated'),
  ('Xerjoff Accento Overdose', 'floral', 'curated'),
  ('Xerjoff Torino 71', 'fresh', 'curated'),
  ('Xerjoff Fiore d''Ulivo', 'fresh', 'curated'),
  ('Xerjoff Dama Bianca', 'floral', 'curated'),
  ('Xerjoff Italica', 'oriental', 'curated'),
  ('Xerjoff Mefisto', 'oriental', 'curated'),
  ('Xerjoff Bouquet Ideale', 'floral', 'curated'),
  ('Xerjoff Lira', 'floral', 'curated'),
  ('Xerjoff Blu Notte', 'floral', 'curated'),
  ('Xerjoff Elle', 'floral', 'curated'),
  ('Xerjoff Wardah', 'oriental', 'curated'),
  ('Xerjoff Azemour les Orangers', 'fresh', 'curated'),
  ('Xerjoff Al Khatt', 'oriental', 'curated'),
  ('Xerjoff Irisss', 'floral', 'curated'),
  ('Xerjoff Don Corleone', 'oriental', 'curated'),
  ('Xerjoff Cruz del Sur II', 'gourmand', 'curated'),
  ('Xerjoff Richwood', 'oriental', 'curated'),
  ('Xerjoff Amber Star', 'oriental', 'curated'),
  ('Xerjoff Roma Uomo', 'fresh', 'curated'),
  ('Xerjoff Roma Donna', 'floral', 'curated'),
  ('Xerjoff Cactus', 'gourmand', 'curated'),
  ('Xerjoff Vanitas', 'gourmand', 'curated'),
  ('Xerjoff Amber Gold', 'oriental', 'curated'),
  ('Xerjoff Kobe', 'oriental', 'curated'),
  ('Xerjoff Muschio di Quercia', 'woody', 'curated'),
  ('Louis Vuitton Imagination', 'fresh', 'curated'),
  ('Louis Vuitton Ombre Nomade', 'oriental', 'curated'),
  ('Louis Vuitton Spell on You', 'gourmand', 'curated'),
  ('Louis Vuitton Afternoon Swim', 'fresh', 'curated'),
  ('Louis Vuitton Nouveau Monde', 'fresh', 'curated'),
  ('Louis Vuitton Sun Song', 'fresh', 'curated'),
  ('Louis Vuitton Turbulences', 'floral', 'curated'),
  ('Louis Vuitton Contre Moi', 'floral', 'curated'),
  ('Louis Vuitton Matière Noire', 'oriental', 'curated'),
  ('Louis Vuitton Météore', 'fresh', 'curated'),
  ('Louis Vuitton Mille Feux', 'gourmand', 'curated'),
  ('Louis Vuitton Rose des Vents', 'floral', 'curated'),
  ('Louis Vuitton Apogée', 'floral', 'curated'),
  ('Louis Vuitton L''Immensité', 'fresh', 'curated'),
  ('Louis Vuitton Dans la Peau', 'oriental', 'curated'),
  ('Louis Vuitton Cactus Garden', 'fresh', 'curated'),
  ('Louis Vuitton Fleur du Désert', 'floral', 'curated'),
  ('Louis Vuitton Au Hasard', 'floral', 'curated'),
  ('Louis Vuitton Orage', 'fresh', 'curated'),
  ('Louis Vuitton Cœur Battant', 'floral', 'curated'),
  ('Louis Vuitton Attrape-Rêves', 'gourmand', 'curated'),
  ('Louis Vuitton Pacific Chill', 'fresh', 'curated'),
  ('Louis Vuitton City of Stars', 'gourmand', 'curated'),
  ('Louis Vuitton Stellar Times', 'oriental', 'curated'),
  ('Yves Saint Laurent Black Opium Extreme', 'gourmand', 'curated'),
  ('Yves Saint Laurent Black Opium Neon', 'gourmand', 'curated'),
  ('Yves Saint Laurent Libre Intense', 'floral', 'curated'),
  ('Yves Saint Laurent Y Le Parfum', 'oriental', 'curated'),
  ('Yves Saint Laurent La Nuit de L''Homme Le Parfum', 'oriental', 'curated'),
  ('Yves Saint Laurent L''Homme', 'fresh', 'curated'),
  ('Yves Saint Laurent L''Homme Ultime', 'oriental', 'curated'),
  ('Yves Saint Laurent Mon Paris', 'floral', 'curated'),
  ('Yves Saint Laurent Mon Paris Intensément', 'gourmand', 'curated'),
  ('Yves Saint Laurent Paris', 'floral', 'curated'),
  ('Yves Saint Laurent Cinema', 'floral', 'curated'),
  ('Yves Saint Laurent Manifesto', 'floral', 'curated'),
  ('Yves Saint Laurent Baby Doll', 'floral', 'curated'),
  ('Giorgio Armani Acqua di Gio Profondo', 'fresh', 'curated'),
  ('Giorgio Armani Acqua di Gio Parfum', 'fresh', 'curated'),
  ('Giorgio Armani Code', 'fresh', 'curated'),
  ('Giorgio Armani Code Absolu', 'oriental', 'curated'),
  ('Giorgio Armani Si', 'floral', 'curated'),
  ('Giorgio Armani Si Passione', 'gourmand', 'curated'),
  ('Giorgio Armani My Way', 'floral', 'curated'),
  ('Giorgio Armani Stronger With You', 'gourmand', 'curated'),
  ('Giorgio Armani Stronger With You Intensely', 'gourmand', 'curated'),
  ('Giorgio Armani Diamonds', 'floral', 'curated'),
  ('Giorgio Armani Eau pour Homme', 'fresh', 'curated'),
  ('Armani Prive Oud Royal', 'oriental', 'curated'),
  ('Armani Prive Rose Alexandrie', 'floral', 'curated'),
  ('Armani Prive Bois d''Encens', 'oriental', 'curated'),
  ('Armani Prive Ambre Soie', 'oriental', 'curated'),
  ('Armani Prive Cuir Amethyste', 'oriental', 'curated'),
  ('Armani Prive Santal Boise', 'woody', 'curated')
on conflict (name) do update set tier = excluded.tier;
