// Wearing guides, part 2: The Scent Handbook, Vol. I Application, Parts VI–IX
// and XI–XV (Part X, the author's own collection, is excluded). English
// follows the handbook; Arabic is a draft (needsReview).

export const WEARING_2 = [
  {
    slug: "longevity-projection-sillage",
    section: "wearing",
    source: { volume: "I", book: "Application", sections: ["Part VI"] },
    en: {
      title: "Longevity, projection and sillage",
      summary: "What actually extends wear, what projection depends on, and how a controlled scent trail is built.",
      body: [
        { h2: "Longevity", id: "longevity" },
        { p: "Highest-value interventions, in order: moisturized skin, strategic clothing application, correct fragrance selection, appropriate concentration, avoiding excess heat exposure, and never relying on your own nose to decide when to reapply." },
        { table: { head: ["Method", "Classification"], rows: [
          ["Moisturized skin", "Scientific / plausible"], ["Clothing application", "Scientific"], ["Higher concentration", "Scientific principle"],
          ["More sprays", "Obvious dose effect"], ["Vaseline", "Plausible"], ["Rubbing to improve performance", "Myth"],
          ["Walking through mist", "Inefficient practice"], ["\"Pulse points fix perfume\"", "Oversimplification"],
          ["Freezing / cooling perfume", "Myth"], ["Applying after exercise for longevity", "Poor practice"],
        ] } },
        { h2: "Projection", id: "projection" },
        { p: "Governed by formula, dose, volatility, temperature and airflow — not simply \"pulse points.\" To increase projection, add one strategically placed spray to exposed skin. Don't add four sprays everywhere." },
        { h2: "Sillage and scent trail", id: "sillage" },
        { p: "The trail left behind as you move is built by back/side neck + shoulders + clothing, because movement creates airflow around these areas." },
        { callout: { kind: "rule", title: "A controlled trail", text: "1 neck + 1 chest + 1 shoulder/clothing — more sophisticated, and more effective, than four sprays at the neck plus four at each wrist." } },
      ],
    },
    ar: {
      needsReview: true,
      title: "الثبات والفوحان والأثر",
      summary: "ما الذي يطيل بقاء العطر فعلًا، وعلامَ يعتمد الفوحان، وكيف يُبنى أثر منضبط.",
      body: [
        { h2: "الثبات", id: "longevity" },
        { p: "أعلى التدخلات قيمة بالترتيب: جلد مرطّب، ثم بخّ استراتيجي على الملابس، ثم اختيار العطر الصحيح، ثم التركيز المناسب، ثم تجنّب التعرّض الزائد للحرارة، وألّا تعتمد أبدًا على أنفك لتقرّر متى تعيد البخّ." },
        { table: { head: ["الطريقة", "التصنيف"], rows: [
          ["جلد مرطّب", "علمي / معقول"], ["البخ على الملابس", "علمي"], ["تركيز أعلى", "مبدأ علمي"],
          ["بخّات أكثر", "أثر جرعة بديهي"], ["الفازلين", "معقول"], ["الفرك لتحسين الأداء", "خرافة"],
          ["المرور عبر الرذاذ", "ممارسة غير فعّالة"], ["«نقاط النبض تثبّت العطر»", "تبسيط مخلّ"],
          ["تجميد / تبريد العطر", "خرافة"], ["البخ بعد التمرين لإطالة الثبات", "ممارسة سيئة"],
        ] } },
        { h2: "الفوحان", id: "projection" },
        { p: "تحكمه التركيبة والجرعة والتطاير والحرارة وحركة الهواء — لا «نقاط النبض» ببساطة. لزيادة الفوحان أضف بخّة واحدة في موضع مدروس على جلد مكشوف. لا تضف أربع بخّات في كل مكان." },
        { h2: "الأثر ومسار الرائحة", id: "sillage" },
        { p: "الأثر الذي تتركه وأنت تتحرك يُبنى من خلف/جانب الرقبة + الكتفين + الملابس، لأن الحركة تخلق تيارًا هوائيًا حول هذه المناطق." },
        { callout: { kind: "rule", title: "أثر منضبط", text: "بخّة على الرقبة + بخّة على الصدر + بخّة على الكتف/الملابس — أرقى وأكثر فاعلية من أربع بخّات على الرقبة وأربع على كل معصم." } },
      ],
    },
  },
  {
    slug: "layering",
    section: "wearing",
    source: { volume: "I", book: "Application", sections: ["Part VII"] },
    en: {
      title: "Layering",
      summary: "What layers well under a fragrance, and the governing principle for fragrance on fragrance: different functions, not competing identities.",
      body: [
        { table: { head: ["Layer", "Verdict", "Note"], rows: [
          ["Unscented moisturizer", "Yes — best universal method", "Supports the surface without altering the fragrance's identity."],
          ["Petroleum jelly", "Yes, selectively", "Use when longevity matters more than projection."],
          ["Matching shower gel", "Usually unnecessary", "Nice ritual; contribution to longevity is overstated."],
          ["Body oil", "Potentially useful", "Unscented only — a scented oil alters the fragrance's profile."],
        ] } },
        { h2: "Fragrance on fragrance", id: "fragrance-on-fragrance" },
        { p: "This is where layering gets genuinely interesting — and genuinely risky. More fragrance is not automatically better fragrance. A dense sweet fragrance stacked on a dense amber one can turn muddy and excessively sweet, while a fresh citrus layered with a woody base can be far more coherent." },
        { callout: { kind: "rule", title: "Governing principle", text: "Layer different functions, not competing identities. Fresh top + woody base — not sweet + sweeter + sweeter." } },
      ],
    },
    ar: {
      needsReview: true,
      title: "الطبقات",
      summary: "ما الذي يصلح طبقةً تحت العطر، والمبدأ الحاكم لعطر فوق عطر: وظائف مختلفة، لا هويات متنافسة.",
      body: [
        { table: { head: ["الطبقة", "الحكم", "ملاحظة"], rows: [
          ["مرطّب بلا رائحة", "نعم — أفضل طريقة عامة", "يدعم السطح دون أن يغيّر هوية العطر."],
          ["الفازلين", "نعم، بانتقائية", "استخدمه حين يهمّ الثبات أكثر من الفوحان."],
          ["جل استحمام مطابق", "غير ضروري غالبًا", "طقس لطيف؛ أثره في الثبات مبالغ فيه."],
          ["زيت الجسم", "قد يكون مفيدًا", "بلا رائحة فقط — الزيت المعطّر يغيّر ملامح العطر."],
        ] } },
        { h2: "عطر فوق عطر", id: "fragrance-on-fragrance" },
        { p: "هنا تصبح الطبقات مثيرة للاهتمام فعلًا — ومحفوفة بالمخاطر فعلًا. المزيد من العطر ليس عطرًا أفضل تلقائيًا. عطر حلو كثيف فوق عطر عنبري كثيف قد يصبح عكرًا ومفرط الحلاوة، بينما حمضيات منعشة فوق قاعدة خشبية قد تكون أكثر انسجامًا بكثير." },
        { callout: { kind: "rule", title: "المبدأ الحاكم", text: "اجعل الطبقات وظائف مختلفة، لا هويات متنافسة. قمة منعشة + قاعدة خشبية — لا حلو + أحلى + أحلى." } },
      ],
    },
  },
  {
    slug: "hot-climates",
    section: "wearing",
    source: { volume: "I", book: "Application", sections: ["Part VIII"] },
    en: {
      title: "Wearing fragrance in hot climates",
      summary: "The Cairo climate framework: fewer sprays as temperature rises, the two-environment problem, and never spraying onto sweating skin.",
      body: [
        { p: "Heat changes the rules — a powerful fragrance that reads as elegant at 22°C can become socially overwhelming at 37°C. This is a climate correction, not a formula correction." },
        { h2: "By temperature", id: "by-temperature" },
        { table: { head: ["Temperature", "Strategy", "Placement"], rows: [
          ["35°C+ (extreme)", "−1 to −2 sprays; controlled diffusion only", "Chest + back/side neck + optional clothing. Avoid wrists, front-neck saturation, heavy layering."],
          ["30–35°C", "2–4 sprays", "1 chest + 1 neck + optional 1 clothing"],
          ["25–30°C", "Comfortable zone — 3–5 sprays", "Standard placement"],
          ["20–25°C", "3–5 sprays; richer fragrances work well", "Standard placement"],
          ["Below 20°C", "3–6 sprays; heavier fragrances more freely", "Concentration still matters"],
        ] } },
        { h2: "The two-environment problem", id: "two-environments" },
        { p: "A Cairo day often moves through 35°C outside into 20–23°C AC indoors — the fragrance experiences two environments in one wear." },
        { callout: { kind: "rule", title: "Dose for the AC, not the street", text: "Strong fragrances: 2–3 sprays. Moderate fragrances: 3–4 sprays." } },
        { h2: "Sweating", id: "sweating" },
        { p: "Never spray heavily onto actively sweating skin — sweat alters odor perception and accelerates fragrance movement. Better sequence: dry skin → fragrance → allow to dry → then dress." },
      ],
    },
    ar: {
      needsReview: true,
      title: "العطر في الأجواء الحارة",
      summary: "إطار مناخ القاهرة: بخّات أقل كلما ارتفعت الحرارة، ومشكلة البيئتين، وألّا تبخّ أبدًا على جلد متعرّق.",
      body: [
        { p: "الحرارة تغيّر القواعد — عطر قوي يبدو أنيقًا عند 22°م قد يصبح طاغيًا اجتماعيًا عند 37°م. هذا تصحيح مناخي، لا تصحيح للتركيبة." },
        { h2: "حسب الحرارة", id: "by-temperature" },
        { table: { head: ["الحرارة", "الاستراتيجية", "المواضع"], rows: [
          ["+35°م (شديدة)", "−1 إلى −2 بخّة؛ انتشار منضبط فقط", "الصدر + خلف/جانب الرقبة + الملابس اختياريًا. تجنّب المعصمين وإغراق مقدمة الرقبة والطبقات الثقيلة."],
          ["30–35°م", "2–4 بخّات", "بخّة على الصدر + بخّة على الرقبة + بخّة على الملابس اختياريًا"],
          ["25–30°م", "منطقة مريحة — 3–5 بخّات", "المواضع المعتادة"],
          ["20–25°م", "3–5 بخّات؛ العطور الأغنى تنجح", "المواضع المعتادة"],
          ["أقل من 20°م", "3–6 بخّات؛ العطور الأثقل بحرية أكبر", "التركيز ما زال مهمًا"],
        ] } },
        { h2: "مشكلة البيئتين", id: "two-environments" },
        { p: "يوم القاهرة كثيرًا ما ينتقل من 35°م في الخارج إلى 20–23°م تحت المكيّف في الداخل — فيعيش العطر بيئتين في وضعة واحدة." },
        { callout: { kind: "rule", title: "اضبط الجرعة للمكيّف، لا للشارع", text: "العطور القوية: 2–3 بخّات. العطور المتوسطة: 3–4 بخّات." } },
        { h2: "التعرّق", id: "sweating" },
        { p: "لا تبخّ بكثرة على جلد يتعرّق — العرق يغيّر إدراك الرائحة ويسرّع حركة العطر. التسلسل الأفضل: جلد جاف ← العطر ← اتركه يجف ← ثم ارتدِ ملابسك." },
      ],
    },
  },
  {
    slug: "fragrance-types",
    section: "wearing",
    source: { volume: "I", book: "Application", sections: ["Part IX"] },
    en: {
      title: "The fragrance-type framework",
      summary: "Starting sprays, placement and overspray risk by type — from fresh citrus to heavy extraits.",
      body: [
        { table: { head: ["Type", "Sprays", "Placement", "Overspray risk"], rows: [
          ["Fresh / citrus", "4–6", "Chest + neck", "Low"], ["Aromatic", "3–5", "Neck + chest", "Medium"], ["Woody", "3–4", "Chest + neck", "Medium"],
          ["Sweet / gourmand", "2–4", "Chest + back neck", "High"], ["Amber", "2–4", "Chest + neck", "High"], ["Oud", "1–3", "Chest / shoulder", "Very high"],
          ["Tobacco", "2–3", "Chest + neck", "High"], ["Heavy extrait", "1–3", "Chest + back neck", "Very high"],
        ] } },
      ],
    },
    ar: {
      needsReview: true,
      title: "إطار أنواع العطور",
      summary: "بخّات البداية والمواضع وخطر الإفراط حسب النوع — من الحمضيات المنعشة إلى الإكستريه الثقيل.",
      body: [
        { table: { head: ["النوع", "البخّات", "المواضع", "خطر الإفراط"], rows: [
          ["منعش / حمضي", "4–6", "الصدر + الرقبة", "منخفض"], ["عطري", "3–5", "الرقبة + الصدر", "متوسط"], ["خشبي", "3–4", "الصدر + الرقبة", "متوسط"],
          ["حلو / غورماند", "2–4", "الصدر + خلف الرقبة", "مرتفع"], ["عنبري", "2–4", "الصدر + الرقبة", "مرتفع"], ["عود", "1–3", "الصدر / الكتف", "مرتفع جدًا"],
          ["تبغ", "2–3", "الصدر + الرقبة", "مرتفع"], ["إكستريه ثقيل", "1–3", "الصدر + خلف الرقبة", "مرتفع جدًا"],
        ] } },
      ],
    },
  },
  {
    slug: "fifteen-mistakes",
    section: "wearing",
    source: { volume: "I", book: "Application", sections: ["Part XI"] },
    en: {
      title: "The 15 biggest mistakes",
      summary: "Ranked by practical impact — and every one is a version of adding more instead of applying better.",
      body: [
        { steps: [
          { title: "Overspraying", text: "The biggest mistake. More fragrance can turn good projection into olfactory aggression." },
          { title: "Reapplying because you can't smell yourself", text: "Olfactory adaptation makes you a poor judge of your own scent." },
          { title: "Applying without moisturizing", text: "Especially noticeable with fragrances that already struggle on dry skin." },
          { title: "Using a heavy fragrance in extreme heat", text: "The formula hasn't changed — the environment has." },
          { title: "Spraying every pulse point", text: "Neck + wrists + elbows + chest + behind ears is unnecessary." },
          { title: "Rubbing wrists", text: "Unnecessary, and alters the early evaporation profile." },
          { title: "Walking through a fragrance cloud", text: "A large share of the product ends up nowhere useful." },
          { title: "Spraying directly onto expensive white clothing", text: "Potential staining or discoloration risk." },
          { title: "Applying to sweaty skin", text: "Poor substrate and poor odor environment." },
          { title: "Layering incompatible fragrances", text: "Can destroy the structure of both." },
          { title: "Using strongly scented moisturizer", text: "Changes the fragrance composition you actually perceive." },
          { title: "Spraying too close", text: "Creates a concentrated wet spot rather than a controlled distribution." },
          { title: "Spraying too far away", text: "Creates unnecessary airborne waste." },
          { title: "Treating pulse points as a universal rule", text: "Pulse points aren't magical fragrance amplifiers." },
          { title: "Choosing performance over context", text: "The most powerful fragrance in an interview is not the most effective one." },
        ] },
        { callout: { kind: "important", title: "The common thread", text: "Every mistake on this list is a version of adding more instead of applying better." } },
      ],
    },
    ar: {
      needsReview: true,
      title: "أكبر 15 خطأ",
      summary: "مرتّبة حسب الأثر العملي — وكلها صورة من صور إضافة المزيد بدل التطبيق الأفضل.",
      body: [
        { steps: [
          { title: "الإفراط في البخ", text: "الخطأ الأكبر. المزيد من العطر قد يحوّل الفوحان الجيد إلى عدوان شمّي." },
          { title: "إعادة البخ لأنك لا تشمّ نفسك", text: "التكيّف الشمّي يجعلك حكمًا ضعيفًا على رائحتك." },
          { title: "البخ دون ترطيب", text: "يظهر خصوصًا مع العطور التي تعاني أصلًا على الجلد الجاف." },
          { title: "عطر ثقيل في حر شديد", text: "التركيبة لم تتغيّر — البيئة هي التي تغيّرت." },
          { title: "البخ على كل نقاط النبض", text: "الرقبة + المعصمان + المرفقان + الصدر + خلف الأذنين غير ضروري." },
          { title: "فرك المعصمين", text: "غير ضروري، ويغيّر منحنى التبخّر المبكر." },
          { title: "المرور عبر سحابة عطر", text: "جزء كبير من العطر ينتهي حيث لا فائدة." },
          { title: "البخ مباشرة على ملابس بيضاء غالية", text: "خطر تبقّع أو تغيّر في اللون." },
          { title: "البخ على جلد متعرّق", text: "سطح ضعيف وبيئة رائحة سيئة." },
          { title: "طبقات من عطور غير متوافقة", text: "قد يهدم بنية العطرين معًا." },
          { title: "مرطّب قوي الرائحة", text: "يغيّر التركيبة العطرية التي تدركها فعلًا." },
          { title: "البخ من مسافة قريبة جدًا", text: "يصنع بقعة مبللة مركّزة بدل توزيع منضبط." },
          { title: "البخ من مسافة بعيدة جدًا", text: "يهدر العطر في الهواء بلا داعٍ." },
          { title: "اعتبار نقاط النبض قاعدة عامة", text: "نقاط النبض ليست مضخّمات سحرية للعطر." },
          { title: "تفضيل الأداء على السياق", text: "أقوى عطر في مقابلة عمل ليس أكثرها فاعلية." },
        ] },
        { callout: { kind: "important", title: "الخيط المشترك", text: "كل خطأ في هذه القائمة صورة من صور إضافة المزيد بدل التطبيق الأفضل." } },
      ],
    },
  },
  {
    slug: "proven-plausible-myth",
    section: "wearing",
    source: { volume: "I", book: "Application", sections: ["Part XII"] },
    en: {
      title: "Proven, plausible, anecdotal, myth",
      summary: "Common claims about wearing fragrance, each with the handbook's verdict.",
      body: [
        { evidence: { label: "Scientific", tone: "scientific" }, text: "Skin properties affect fragrance evaporation." },
        { evidence: { label: "Scientific", tone: "scientific" }, text: "Fragrance ingredients evaporate at different rates." },
        { evidence: { label: "Scientific", tone: "scientific" }, text: "Temperature affects evaporation." },
        { evidence: { label: "Scientific", tone: "scientific" }, text: "Fabric can retain fragrance longer." },
        { evidence: { label: "Plausible", tone: "plausible" }, text: "Moisturized skin can improve persistence." },
        { evidence: { label: "Scientific", tone: "scientific" }, text: "Fragrance develops differently on different people." },
        { evidence: { label: "Scientific", tone: "scientific" }, text: "Clothing produces longer persistence." },
        { evidence: { label: "Myth", tone: "myth" }, text: "Vaseline makes perfume last forever." },
        { evidence: { label: "Myth", tone: "myth" }, text: "Pulse points magically activate perfume." },
        { evidence: { label: "Myth", tone: "myth" }, text: "Rubbing \"destroys\" perfume." },
        { evidence: { label: "Poor practice", tone: "practice" }, text: "Walking through a mist improves performance." },
        { evidence: { label: "Myth", tone: "myth" }, text: "Spraying upward makes perfume project better." },
        { evidence: { label: "Myth", tone: "myth" }, text: "More sprays always means better performance." },
        { evidence: { label: "Anecdotal", tone: "anecdotal" }, text: "Drinking water dramatically increases longevity." },
        { evidence: { label: "Mostly myth", tone: "myth" }, text: "Refrigerating perfume improves it." },
        { evidence: { label: "Poor practice", tone: "practice" }, text: "Applying right after a hot shower is optimal." },
        { p: "The literature supports the broader picture: evaporation is governed by the physicochemical properties of the ingredients, the vehicle, the skin and the environment — not by simplistic \"pulse point\" rules." },
      ],
    },
    ar: {
      needsReview: true,
      title: "مثبت، معقول، روايات، خرافة",
      summary: "ادعاءات شائعة عن وضع العطر، ولكلٍّ منها حكم الدليل.",
      body: [
        { evidence: { label: "علمي", tone: "scientific" }, text: "خصائص الجلد تؤثر في تبخّر العطر." },
        { evidence: { label: "علمي", tone: "scientific" }, text: "مكوّنات العطر تتبخّر بمعدلات مختلفة." },
        { evidence: { label: "علمي", tone: "scientific" }, text: "الحرارة تؤثر في التبخّر." },
        { evidence: { label: "علمي", tone: "scientific" }, text: "القماش قد يحتفظ بالعطر مدة أطول." },
        { evidence: { label: "معقول", tone: "plausible" }, text: "الجلد المرطّب قد يحسّن الثبات." },
        { evidence: { label: "علمي", tone: "scientific" }, text: "العطر يتطوّر بشكل مختلف على أشخاص مختلفين." },
        { evidence: { label: "علمي", tone: "scientific" }, text: "الملابس تمنح ثباتًا أطول." },
        { evidence: { label: "خرافة", tone: "myth" }, text: "الفازلين يجعل العطر يدوم إلى الأبد." },
        { evidence: { label: "خرافة", tone: "myth" }, text: "نقاط النبض تنشّط العطر بشكل سحري." },
        { evidence: { label: "خرافة", tone: "myth" }, text: "الفرك «يدمّر» العطر." },
        { evidence: { label: "ممارسة سيئة", tone: "practice" }, text: "المرور عبر الرذاذ يحسّن الأداء." },
        { evidence: { label: "خرافة", tone: "myth" }, text: "البخ نحو الأعلى يجعل العطر يفوح أكثر." },
        { evidence: { label: "خرافة", tone: "myth" }, text: "المزيد من البخّات يعني دائمًا أداءً أفضل." },
        { evidence: { label: "روايات", tone: "anecdotal" }, text: "شرب الماء يطيل الثبات بشكل كبير." },
        { evidence: { label: "خرافة في الغالب", tone: "myth" }, text: "حفظ العطر في الثلاجة يحسّنه." },
        { evidence: { label: "ممارسة سيئة", tone: "practice" }, text: "البخ مباشرة بعد حمام ساخن هو الأمثل." },
        { p: "تدعم الأدبيات الصورة الأوسع: التبخّر تحكمه الخصائص الفيزيائية والكيميائية للمكوّنات والناقل والجلد والبيئة — لا قواعد «نقاط النبض» المبسّطة." },
      ],
    },
  },
  {
    slug: "sixty-second-protocol",
    section: "wearing",
    source: { volume: "I", book: "Application", sections: ["Part XIII", "Part XIV", "Part XV"] },
    en: {
      title: "The 60-second protocol",
      summary: "The application protocol in under a minute, three wear profiles, and the closing rule with the olfactory radius.",
      body: [
        { h2: "The perfect application protocol", id: "protocol" },
        { steps: [
          { title: "Prepare", text: "Clean, completely dry skin. If possible: unscented moisturizer, then wait 2–5 minutes." },
          { title: "Spray distance", text: "Hold the bottle 10–15 cm (4–6 in) from skin." },
          { title: "Apply", text: "Use the minimum effective dose. Default for a strong fragrance: 3 sprays — 1 chest, 1 left/right neck." },
          { title: "Optional fabric", text: "1 light spray on inner or dark clothing for longevity — never on a white or delicate visible surface." },
          { title: "Don't touch", text: "No rubbing, no wiping, no pressing. Let it dry naturally." },
          { title: "Dress", text: "Ideally, fragrance → 30–60 seconds → clothing. Not mandatory, but minimizes unnecessary transfer." },
          { title: "Performance check", text: "Do not smell your wrist immediately. Wait 15–30 minutes, then evaluate from a normal distance." },
        ] },
        { h2: "Three wear profiles", id: "wear-profiles" },
        { table: { head: ["Profile", "Goal", "Application"], rows: [
          ["I — Everyday", "Noticeable but controlled", "Unscented moisturizer. 3 sprays — 1 chest, 1 left neck, 1 right neck. Optional 1 clothing spray for weaker fragrances. For errands, casual outings, restaurants, shopping, daytime."],
          ["II — Professional / office", "A clean personal scent bubble", "Unscented moisturizer. 2–3 sprays — 1 chest, 1 back neck, optional 1 shoulder. Clothing usually unnecessary."],
          ["III — Maximum performance", "Maximum effective performance without becoming obnoxious", "Shower → dry → unscented moisturizer → wait 2–5 min. 3–4 sprays — 1 chest, 1 each side/back neck, 1 shoulder. Optional 1 controlled clothing spray. 4–5 applications maximum for most strong fragrances."],
        ] } },
        { callout: { kind: "rule", title: "The office rule", text: "People should discover the fragrance when they enter your space — not when you enter theirs. Essential for interviews, sales settings and enclosed offices." } },
        { p: "For dense compositions, 3 skin sprays may already be \"maximum performance.\"" },
        { h2: "The closing rule", id: "closing-rule" },
        { callout: { kind: "rule", title: "If one system is remembered", text: "Hydrate → 2–3 strategic skin sprays → 1 optional fabric spray → don't rub → let airflow work. Prioritize locations in this order — chest → neck → shoulder → clothing — not wrists → elbows → behind ears → everywhere." } },
        { h2: "The olfactory radius", id: "olfactory-radius" },
        { table: { head: ["Distance", "Presence"], rows: [["0–30 cm", "Clearly recognizable"], ["30–100 cm", "Pleasant diffusion"], ["1 m+", "Occasional sillage"], ["Beyond", "Generally unnecessary for professional wear"]] } },
        { quote: "The objective is not the largest possible scent cloud — it is a controlled olfactory radius." },
      ],
    },
    ar: {
      needsReview: true,
      title: "بروتوكول الستين ثانية",
      summary: "بروتوكول وضع العطر في أقل من دقيقة، وثلاثة أنماط للارتداء، والقاعدة الختامية مع نطاق الرائحة.",
      body: [
        { h2: "البروتوكول المثالي", id: "protocol" },
        { steps: [
          { title: "التجهيز", text: "جلد نظيف وجاف تمامًا. إن أمكن: مرطّب بلا رائحة، ثم انتظر 2–5 دقائق." },
          { title: "مسافة البخ", text: "أمسك الزجاجة على بعد 10–15 سم من الجلد." },
          { title: "البخ", text: "استخدم أقل جرعة فعّالة. الافتراضي لعطر قوي: 3 بخّات — واحدة على الصدر، وواحدة على كل جانب من الرقبة." },
          { title: "القماش اختياريًا", text: "بخّة خفيفة واحدة على الملابس الداخلية أو الداكنة لإطالة الثبات — لا على سطح أبيض أو رقيق ظاهر أبدًا." },
          { title: "لا تلمس", text: "لا فرك ولا مسح ولا ضغط. اتركه يجف طبيعيًا." },
          { title: "ارتدِ ملابسك", text: "الأفضل: العطر ← 30–60 ثانية ← الملابس. ليس إلزاميًا، لكنه يقلّل الانتقال غير الضروري." },
          { title: "فحص الأداء", text: "لا تشمّ معصمك فورًا. انتظر 15–30 دقيقة، ثم قيّم من مسافة عادية." },
        ] },
        { h2: "ثلاثة أنماط للارتداء", id: "wear-profiles" },
        { table: { head: ["النمط", "الهدف", "الطريقة"], rows: [
          ["I — يومي", "ملحوظ لكن منضبط", "مرطّب بلا رائحة. 3 بخّات — واحدة على الصدر وواحدة على كل جانب من الرقبة. بخّة اختيارية على الملابس للعطور الأضعف. للمشاوير والنزهات والمطاعم والتسوّق والنهار."],
          ["II — مهني / مكتب", "هالة رائحة شخصية نظيفة", "مرطّب بلا رائحة. 2–3 بخّات — واحدة على الصدر وواحدة خلف الرقبة وواحدة على الكتف اختياريًا. الملابس غير ضرورية غالبًا."],
          ["III — أقصى أداء", "أقصى أداء فعّال دون أن يصبح مزعجًا", "استحمام ← تجفيف ← مرطّب بلا رائحة ← انتظر 2–5 دقائق. 3–4 بخّات — واحدة على الصدر، وواحدة على كل جانب/خلف الرقبة، وواحدة على الكتف. بخّة منضبطة اختيارية على الملابس. 4–5 مرات كحد أقصى لمعظم العطور القوية."],
        ] } },
        { callout: { kind: "rule", title: "قاعدة المكتب", text: "يجب أن يكتشف الناس العطر حين يدخلون مساحتك — لا حين تدخل مساحتهم. ضرورية للمقابلات وبيئات البيع والمكاتب المغلقة." } },
        { p: "مع التركيبات الكثيفة، قد تكون 3 بخّات على الجلد هي «أقصى أداء» بالفعل." },
        { h2: "القاعدة الختامية", id: "closing-rule" },
        { callout: { kind: "rule", title: "إن تذكّرت نظامًا واحدًا", text: "رطّب ← 2–3 بخّات مدروسة على الجلد ← بخّة اختيارية على القماش ← لا تفرك ← دع الهواء يعمل. رتّب المواضع هكذا — الصدر ← الرقبة ← الكتف ← الملابس — لا المعصمين ← المرفقين ← خلف الأذنين ← كل مكان." } },
        { h2: "نطاق الرائحة", id: "olfactory-radius" },
        { table: { head: ["المسافة", "الحضور"], rows: [["0–30 سم", "واضح التمييز"], ["30–100 سم", "انتشار لطيف"], ["+1 م", "أثر عابر"], ["أبعد من ذلك", "غير ضروري عمومًا في بيئة العمل"]] } },
        { quote: "الهدف ليس أكبر سحابة رائحة ممكنة — بل نطاق رائحة منضبط." },
      ],
    },
  },
];
