// Wearing guides, part 1: The Scent Handbook, Vol. I Application, Parts I–V.
// English follows the handbook; Arabic is a draft (needsReview).
// { evidence: { label, tone }, title, text } shows the handbook's own
// evidence label verbatim; `tone` only picks the badge colour.

export const WEARING_1 = [
  {
    slug: "how-fragrance-works",
    section: "wearing",
    source: { volume: "I", book: "Application", sections: ["Part I"] },
    en: {
      title: "How fragrance actually works",
      summary: "Perceived performance is a product of composition, concentration, dose, skin, temperature and airflow — pull one lever too hard and the others suffer.",
      body: [
        { formula: ["Composition × Concentration × Dose × Skin Interaction × Temperature × Airflow"] },
        { p: "Perceived performance is not a single lever — it is a product of composition, concentration, deposited dose, skin interaction, temperature and airflow. Pull any one lever too hard and the others suffer." },
        { h2: "Skin chemistry", id: "skin-chemistry" },
        { evidence: { label: "Scientific evidence", tone: "scientific" }, text: "People genuinely experience fragrances differently — measured differences in evaporation between individuals have been linked to both molecular properties and skin characteristics. But \"skin chemistry completely changes the fragrance\" is exaggerated: the fragrance's molecular composition remains the dominant factor." },
        { h2: "Skin hydration", id: "skin-hydration" },
        { evidence: { label: "Plausible / professional practice", tone: "plausible" }, text: "Dry skin is a poor substrate for retaining volatile material. A moisturized surface helps fragrance remain available at the skin for longer. Practical conclusion: apply fragrance to clean, moisturized skin — preferably with an unscented moisturizer." },
        { h2: "Body temperature", id: "body-temperature" },
        { evidence: { label: "Scientific evidence", tone: "scientific" }, text: "Heat increases evaporation. \"Hot pulse points make perfume last longer\" is incomplete — more heat means faster release, stronger initial diffusion, and potentially shorter persistence." },
        { h2: "Concentration", id: "concentration" },
        { evidence: { label: "Scientific principle", tone: "scientific" }, text: "EDT, EDP, parfum and extrait are not simply \"strength levels.\" A dense extrait can project less than a diffusive EDP while lasting far longer — formula composition matters more than the label." },
        { h2: "Volatility", id: "volatility" },
        { evidence: { label: "Scientific evidence", tone: "scientific" }, text: "Ingredients evaporate at markedly different rates, and interactions between them alter the evaporation profile further. This is the real mechanism behind Opening → Heart → Base — not marketing terminology." },
        { h2: "Environment and airflow", id: "airflow" },
        { evidence: { label: "Physical principle", tone: "scientific" }, text: "Air movement carries molecules away from the skin. AC and wind increase dispersion; an enclosed room lets scent accumulate. The same five sprays behave differently indoors and outdoors." },
        { h2: "Humidity", id: "humidity" },
        { evidence: { label: "Professional practice", tone: "practice" }, text: "\"High humidity always increases projection\" is too simplistic. In Cairo, the dominant factor is almost always heat + sweating + airflow + enclosed AC — not humidity alone." },
        { callout: { kind: "important", title: "Carried forward", text: "Skin properties, evaporation rates, temperature and airflow set the ceiling — technique decides how close you get to it." } },
      ],
    },
    ar: {
      needsReview: true,
      title: "كيف يعمل العطر فعلًا",
      summary: "الأداء الذي نلمسه حاصل ضرب التركيبة والتركيز والجرعة والجلد والحرارة وحركة الهواء — شدّ أي رافعة أكثر من اللازم وتتأثر البقية.",
      body: [
        { formula: ["Composition × Concentration × Dose × Skin Interaction × Temperature × Airflow"] },
        { p: "الأداء الذي نلمسه ليس رافعة واحدة — إنه حاصل التركيبة والتركيز والجرعة المترسّبة وتفاعل الجلد والحرارة وحركة الهواء. شدّ أي رافعة أكثر من اللازم وتتأثر البقية." },
        { h2: "كيمياء الجلد", id: "skin-chemistry" },
        { evidence: { label: "دليل علمي", tone: "scientific" }, text: "يختبر الناس العطور فعلًا بشكل مختلف — وقد رُبطت فروق مقيسة في التبخّر بين الأفراد بخصائص الجزيئات وخصائص الجلد معًا. لكن عبارة «كيمياء الجلد تغيّر العطر تمامًا» مبالغ فيها: يبقى التركيب الجزيئي للعطر هو العامل المهيمن." },
        { h2: "ترطيب الجلد", id: "skin-hydration" },
        { evidence: { label: "معقول / ممارسة مهنية", tone: "plausible" }, text: "الجلد الجاف سطح ضعيف للاحتفاظ بالمواد المتطايرة. السطح المرطّب يساعد العطر على البقاء متاحًا على الجلد مدة أطول. الخلاصة العملية: ضع العطر على جلد نظيف مرطّب — ويفضّل بمرطّب بلا رائحة." },
        { h2: "حرارة الجسم", id: "body-temperature" },
        { evidence: { label: "دليل علمي", tone: "scientific" }, text: "الحرارة تزيد التبخّر. عبارة «نقاط النبض الساخنة تطيل بقاء العطر» ناقصة — فالحرارة الأعلى تعني انطلاقًا أسرع وانتشارًا أوليًا أقوى، وربما ثباتًا أقصر." },
        { h2: "التركيز", id: "concentration" },
        { evidence: { label: "مبدأ علمي", tone: "scientific" }, text: "EDT وEDP والبارفان والإكستريه ليست مجرد «مستويات قوة». قد يفوح إكستريه كثيف أقل من EDP منتشر بينما يدوم أطول بكثير — تركيبة العطر أهم من التسمية." },
        { h2: "التطاير", id: "volatility" },
        { evidence: { label: "دليل علمي", tone: "scientific" }, text: "تتبخّر المكوّنات بمعدلات مختلفة جدًا، والتفاعلات بينها تغيّر منحنى التبخّر أكثر. هذه هي الآلية الحقيقية وراء الافتتاحية ← القلب ← القاعدة — لا مصطلحات تسويقية." },
        { h2: "البيئة وحركة الهواء", id: "airflow" },
        { evidence: { label: "مبدأ فيزيائي", tone: "scientific" }, text: "حركة الهواء تحمل الجزيئات بعيدًا عن الجلد. المكيّف والرياح يزيدان التشتت؛ والغرفة المغلقة تجعل الرائحة تتراكم. البخّات الخمس نفسها تتصرف بشكل مختلف داخل المكان وخارجه." },
        { h2: "الرطوبة", id: "humidity" },
        { evidence: { label: "ممارسة مهنية", tone: "practice" }, text: "عبارة «الرطوبة العالية تزيد الفوحان دائمًا» تبسيط مخلّ. في القاهرة يكون العامل المهيمن دائمًا تقريبًا الحرارة + التعرّق + حركة الهواء + المكيّف في الأماكن المغلقة — لا الرطوبة وحدها." },
        { callout: { kind: "important", title: "خلاصة", text: "خصائص الجلد ومعدلات التبخّر والحرارة وحركة الهواء تحدد السقف — والتقنية تحدد مدى اقترابك منه." } },
      ],
    },
  },
  {
    slug: "skin-preparation",
    section: "wearing",
    source: { volume: "I", book: "Application", sections: ["Part II"] },
    en: {
      title: "Skin preparation",
      summary: "The sequence before the first spray, and what moisturizers, petroleum jelly, oils and shower temperature really do.",
      body: [
        { h2: "The optimal sequence", id: "sequence" },
        { steps: [
          { title: "Standard", text: "Shower → Dry completely → Unscented moisturizer → Wait 2–5 minutes → Fragrance → Dress." },
          { title: "Already dressed", text: "Moisturize exposed areas → Let settle → Fragrance." },
        ] },
        { h2: "Unscented moisturizer", id: "moisturizer" },
        { evidence: { label: "Proven / plausible", tone: "scientific" }, text: "The single most valuable preparation step. A thin, hydrated, lipid-containing layer alters how fragrance molecules interact with skin and reduces immediate loss of volatile material. Use a thin layer, not a greasy coating — shower, dry thoroughly, apply lotion, wait 2–5 minutes, then apply fragrance." },
        { h2: "Petroleum jelly", id: "petroleum-jelly" },
        { evidence: { label: "Plausible — frequently exaggerated", tone: "plausible" }, text: "Highly occlusive and capable of altering evaporation, but not a magical fixative. It can create a heavier application surface and change how the opening diffuses. Use occasionally for longevity, not projection — a tiny amount, thin film, fragrance on top." },
        { h2: "Body oils", id: "body-oils" },
        { evidence: { label: "Plausible", tone: "plausible" }, text: "A light, unscented oil offers a more occlusive surface, but is not automatically superior to lotion. Daily ranking: unscented lotion > body oil > heavy petrolatum for practicality." },
        { h2: "Shower temperature", id: "shower" },
        { evidence: { label: "Professional practice", tone: "practice" }, text: "A very hot shower raises skin temperature and can make the opening evaporate faster. Better: warm shower → dry completely → let skin temperature normalize → moisturize → fragrance. Deliberate cooling isn't necessary." },
      ],
    },
    ar: {
      needsReview: true,
      title: "تجهيز الجلد",
      summary: "التسلسل قبل البخّة الأولى، وما تفعله فعلًا المرطّبات والفازلين والزيوت وحرارة الاستحمام.",
      body: [
        { h2: "التسلسل الأمثل", id: "sequence" },
        { steps: [
          { title: "المعتاد", text: "استحمام ← تجفيف تام ← مرطّب بلا رائحة ← انتظر 2–5 دقائق ← العطر ← ارتدِ ملابسك." },
          { title: "إن كنت ترتدي ملابسك", text: "رطّب المناطق المكشوفة ← اتركه يستقر ← العطر." },
        ] },
        { h2: "مرطّب بلا رائحة", id: "moisturizer" },
        { evidence: { label: "مثبت / معقول", tone: "scientific" }, text: "أهم خطوة تجهيز على الإطلاق. طبقة رقيقة مرطّبة تحتوي على دهون تغيّر طريقة تفاعل جزيئات العطر مع الجلد وتقلّل الفقد الفوري للمواد المتطايرة. استخدم طبقة رقيقة لا طبقة دهنية — استحم، جفّف جيدًا، ضع اللوشن، انتظر 2–5 دقائق، ثم ضع العطر." },
        { h2: "الفازلين", id: "petroleum-jelly" },
        { evidence: { label: "معقول — كثيرًا ما يُبالغ فيه", tone: "plausible" }, text: "عازل بقوة وقادر على تغيير التبخّر، لكنه ليس مثبّتًا سحريًا. قد يخلق سطحًا أثقل للتطبيق ويغيّر طريقة انتشار الافتتاحية. استخدمه أحيانًا للثبات لا للفوحان — كمية ضئيلة، طبقة رقيقة، والعطر فوقها." },
        { h2: "زيوت الجسم", id: "body-oils" },
        { evidence: { label: "معقول", tone: "plausible" }, text: "الزيت الخفيف بلا رائحة يوفّر سطحًا أكثر عزلًا، لكنه ليس أفضل من اللوشن تلقائيًا. الترتيب اليومي من حيث العملية: لوشن بلا رائحة > زيت الجسم > الفازلين الثقيل." },
        { h2: "حرارة الاستحمام", id: "shower" },
        { evidence: { label: "ممارسة مهنية", tone: "practice" }, text: "الاستحمام بماء شديد السخونة يرفع حرارة الجلد وقد يجعل الافتتاحية تتبخّر أسرع. الأفضل: ماء دافئ ← تجفيف تام ← دع حرارة الجلد تعتدل ← رطّب ← العطر. التبريد المتعمد ليس ضروريًا." },
      ],
    },
  },
  {
    slug: "where-to-spray",
    section: "wearing",
    source: { volume: "I", book: "Application", sections: ["Part III"] },
    en: {
      title: "Where to spray",
      summary: "A small number of high-value locations outperforms broad coverage: chest, neck, shoulders, and one controlled clothing spray.",
      body: [
        { p: "Forget the idea that perfume belongs everywhere. A small number of high-value locations outperforms broad, indiscriminate coverage." },
        { h2: "The four locations", id: "locations" },
        { steps: [
          { title: "Chest", text: "Controlled warmth, fabric interaction, upward diffusion. The single highest-value location; excellent for office wear." },
          { title: "Neck (side / back)", text: "Air movement, constant exposure, close to others' breathing zone. 1 spray each side, or 1 center/back — never saturate the whole neck." },
          { title: "Shoulders", text: "Excellent for controlled sillage under clothing; produces a subtle scent field as you move. Ideal for office / formal / close-contact settings." },
          { title: "One controlled clothing spray", text: "Inner collar or inner jacket, when persistence matters more than skin evolution." },
        ] },
        { h2: "Other places", id: "other-places" },
        { table: { head: ["Location", "Verdict", "Note"], rows: [
          ["Behind the ears", "Useful, not essential", "Skip for powerful fragrances; 1 light spray for subtle ones."],
          ["Wrists", "Overrated", "Constantly washed, rubbed and moved — chest + neck outperform."],
          ["Forearms", "Good secondary", "Useful in short sleeves only; don't add by default."],
          ["Hair", "Useful with caution", "Alcohol is drying — mist a brush and pass through hair instead."],
        ] } },
        { h2: "Distance, direction and contact", id: "technique" },
        { list: [
          "Spray distance — 10–15 cm (4–6 in). Fine, controlled distribution, not a concentrated wet spot.",
          "Direct spray, not misting — target the skin directly; walking through a cloud wastes most of the product.",
          "Spray direction — essentially irrelevant. Distance, target, dose and coverage matter; up vs. down does not.",
        ] },
        { evidence: { label: "Myth", tone: "myth" }, title: "Rubbing \"destroys\" the fragrance", text: "Friction adds heat and can accelerate the opening's evaporation — spray, then leave untouched to dry naturally." },
      ],
    },
    ar: {
      needsReview: true,
      title: "أين تبخّ العطر",
      summary: "عدد قليل من المواضع عالية القيمة يتفوّق على التغطية الواسعة: الصدر والرقبة والكتفان وبخّة واحدة منضبطة على الملابس.",
      body: [
        { p: "انسَ فكرة أن العطر مكانه في كل مكان. عدد قليل من المواضع عالية القيمة يتفوّق على التغطية الواسعة العشوائية." },
        { h2: "المواضع الأربعة", id: "locations" },
        { steps: [
          { title: "الصدر", text: "دفء منضبط وتفاعل مع القماش وانتشار نحو الأعلى. أعلى المواضع قيمة؛ ممتاز للمكتب." },
          { title: "الرقبة (الجانب / الخلف)", text: "حركة هواء وتعرّض دائم وقرب من منطقة تنفّس الآخرين. بخّة واحدة لكل جانب، أو واحدة في المنتصف/الخلف — لا تغرق الرقبة كلها أبدًا." },
          { title: "الكتفان", text: "ممتازان لأثر منضبط تحت الملابس؛ يصنعان هالة رائحة خفيفة وأنت تتحرك. مثاليان للمكتب والمناسبات الرسمية والتواصل القريب." },
          { title: "بخّة واحدة منضبطة على الملابس", text: "الياقة من الداخل أو بطانة السترة، حين يهمّ الثبات أكثر من تطوّر العطر على الجلد." },
        ] },
        { h2: "مواضع أخرى", id: "other-places" },
        { table: { head: ["الموضع", "الحكم", "ملاحظة"], rows: [
          ["خلف الأذنين", "مفيد، غير ضروري", "تجاوزه مع العطور القوية؛ بخّة خفيفة واحدة للعطور الهادئة."],
          ["المعصمان", "مبالغ في قيمتهما", "يُغسلان ويُفركان ويتحركان باستمرار — الصدر والرقبة أفضل."],
          ["الساعدان", "خيار ثانوي جيد", "مفيدان مع الأكمام القصيرة فقط؛ لا تضفهما افتراضيًا."],
          ["الشعر", "مفيد بحذر", "الكحول يجفّف — بخّ الفرشاة وامرّرها في الشعر بدلًا من ذلك."],
        ] } },
        { h2: "المسافة والاتجاه واللمس", id: "technique" },
        { list: [
          "مسافة البخ — 10–15 سم. توزيع دقيق منضبط، لا بقعة مبللة مركّزة.",
          "بخّ مباشر لا رذاذ — استهدف الجلد مباشرة؛ المرور عبر سحابة يهدر معظم العطر.",
          "اتجاه البخ — لا أهمية تُذكر له. المهم المسافة والهدف والجرعة والتغطية؛ لا الأعلى ولا الأسفل.",
        ] },
        { evidence: { label: "خرافة", tone: "myth" }, title: "الفرك «يدمّر» العطر", text: "الاحتكاك يضيف حرارة وقد يسرّع تبخّر الافتتاحية — بخّ ثم اتركه يجف طبيعيًا دون لمس." },
      ],
    },
  },
  {
    slug: "spray-count",
    section: "wearing",
    source: { volume: "I", book: "Application", sections: ["Part IV"] },
    en: {
      title: "The spray-count system",
      summary: "Starting doses by strength, and how the situation adjusts them. Spray count is a starting dose, not a measurement.",
      body: [
        { callout: { kind: "important", title: "Read this first", text: "Spray counts are approximate — atomizers differ, sometimes by an order of magnitude. Treat every number below as a starting dose, not a measurement. Spray count ≠ performance." } },
        { h2: "Starting range by strength", id: "by-strength" },
        { table: { head: ["Strength", "Sprays"], rows: [["Weak / subtle", "5–7"], ["Moderate", "3–5"], ["Strong", "2–4"], ["Parfum / Extrait", "1–3"], ["Extremely powerful niche", "1–2"]] } },
        { h2: "Context adjustment", id: "context" },
        { table: { head: ["Situation", "Adjustment"], rows: [
          ["Extreme Cairo heat", "−1 to −2 sprays"], ["Moderate heat", "Normal"], ["Cool weather", "+1 spray if necessary"],
          ["High humidity", "Usually normal or −1"], ["Strong AC", "Normal"], ["Outdoor", "+1 if fragrance is moderate"],
          ["Office", "−1 to −2"], ["Date", "Normal"], ["Formal event", "Normal / slightly increased"], ["Interview", "Conservative"],
        ] } },
        { quote: "The environment determines how quickly a fragrance becomes socially noticeable — not the bottle." },
      ],
    },
    ar: {
      needsReview: true,
      title: "نظام عدد البخّات",
      summary: "جرعات البداية حسب القوة، وكيف يعدّلها الموقف. عدد البخّات جرعة بداية لا قياس.",
      body: [
        { callout: { kind: "important", title: "اقرأ هذا أولًا", text: "أعداد البخّات تقريبية — البخّاخات تختلف، أحيانًا بعشرة أضعاف. تعامل مع كل رقم أدناه كجرعة بداية لا كقياس. عدد البخّات ≠ الأداء." } },
        { h2: "نطاق البداية حسب القوة", id: "by-strength" },
        { table: { head: ["القوة", "البخّات"], rows: [["ضعيف / هادئ", "5–7"], ["متوسط", "3–5"], ["قوي", "2–4"], ["بارفان / إكستريه", "1–3"], ["عطر نيش قوي جدًا", "1–2"]] } },
        { h2: "التعديل حسب الموقف", id: "context" },
        { table: { head: ["الموقف", "التعديل"], rows: [
          ["حر القاهرة الشديد", "−1 إلى −2 بخّة"], ["حرارة معتدلة", "عادي"], ["طقس بارد", "+1 بخّة عند الحاجة"],
          ["رطوبة عالية", "عادي غالبًا أو −1"], ["مكيّف قوي", "عادي"], ["في الخارج", "+1 إن كان العطر متوسطًا"],
          ["المكتب", "−1 إلى −2"], ["موعد", "عادي"], ["مناسبة رسمية", "عادي / زيادة طفيفة"], ["مقابلة عمل", "متحفّظ"],
        ] } },
        { quote: "البيئة هي التي تحدد سرعة ملاحظة الآخرين للعطر — لا الزجاجة." },
      ],
    },
  },
  {
    slug: "skin-vs-clothing",
    section: "wearing",
    source: { volume: "I", book: "Application", sections: ["Part V"] },
    en: {
      title: "Skin vs clothing",
      summary: "What each surface gives you, when to choose one, and the hybrid system: 2–3 sprays on skin plus one on clothing.",
      body: [
        { table: { head: ["Factor", "Skin", "Clothing"], rows: [
          ["Longevity", "Good", "Excellent"], ["Projection", "Excellent initially", "Moderate / steady"], ["Sillage", "Excellent", "Good"],
          ["Development", "Excellent", "Limited"], ["Skin interaction", "Yes", "No"], ["Staining risk", "Very low", "Possible"],
          ["Best for", "Full fragrance experience", "Persistence"],
        ] } },
        { evidence: { label: "Scientific evidence", tone: "scientific" }, text: "Fragrance compounds persist on fabric considerably longer than on skin; fabric type measurably affects transfer and persistence." },
        { h2: "Skin only, best when", id: "skin-only" },
        { list: ["Fragrance is powerful", "Office environment or interview", "Close-contact situation", "Delicate clothing", "You want the full evolution"] },
        { h2: "Clothing only, best when", id: "clothing-only" },
        { list: ["Maximum persistence matters", "Fragrance performs poorly on your skin", "Outerwear is being used"] },
        { p: "Trade-off: you sacrifice much of the skin-development arc." },
        { h2: "Preferred system — hybrid", id: "hybrid" },
        { callout: { kind: "rule", title: "2–3 sprays skin + 1 clothing spray", text: "Skin evolution plus fabric persistence, without reaching for 6–10 sprays. Use cotton, darker fabrics, the inner collar or inner jacket, and areas unlikely to visibly mark. Avoid white shirts, silk, suede, leather and delicate or expensive light-colored garments — resinous, vanilla-rich or strongly colored compositions can discolor fabric." } },
      ],
    },
    ar: {
      needsReview: true,
      title: "الجلد أم الملابس",
      summary: "ما يمنحه كل سطح، ومتى تختار أحدهما، والنظام الهجين: 2–3 بخّات على الجلد وواحدة على الملابس.",
      body: [
        { table: { head: ["العامل", "الجلد", "الملابس"], rows: [
          ["الثبات", "جيد", "ممتاز"], ["الفوحان", "ممتاز في البداية", "متوسط / ثابت"], ["الأثر", "ممتاز", "جيد"],
          ["التطوّر", "ممتاز", "محدود"], ["التفاعل مع الجلد", "نعم", "لا"], ["خطر التبقّع", "منخفض جدًا", "وارد"],
          ["الأفضل لـ", "تجربة العطر كاملة", "الثبات"],
        ] } },
        { evidence: { label: "دليل علمي", tone: "scientific" }, text: "تبقى مركّبات العطر على القماش مدة أطول بكثير من الجلد؛ ونوع القماش يؤثر بشكل مقيس في الانتقال والثبات." },
        { h2: "الجلد وحده أفضل حين", id: "skin-only" },
        { list: ["يكون العطر قويًا", "تكون في بيئة مكتب أو مقابلة عمل", "يكون التواصل قريبًا", "تكون الملابس رقيقة", "تريد التطوّر الكامل للعطر"] },
        { h2: "الملابس وحدها أفضل حين", id: "clothing-only" },
        { list: ["يهمّ أقصى ثبات", "يكون أداء العطر ضعيفًا على جلدك", "ترتدي ملابس خارجية"] },
        { p: "المقابل: تضحّي بجزء كبير من مسار تطوّر العطر على الجلد." },
        { h2: "النظام المفضّل — الهجين", id: "hybrid" },
        { callout: { kind: "rule", title: "2–3 بخّات على الجلد + بخّة على الملابس", text: "تطوّر على الجلد مع ثبات على القماش، دون الحاجة إلى 6–10 بخّات. استخدم القطن والأقمشة الداكنة وداخل الياقة أو بطانة السترة ومناطق لا يظهر عليها أثر. تجنّب القمصان البيضاء والحرير والشامواه والجلد والملابس الرقيقة أو الغالية فاتحة اللون — فالتركيبات الراتنجية أو الغنية بالفانيليا أو القوية اللون قد تغيّر لون القماش." } },
      ],
    },
  },
];
